# Basic website settings
title: "Stanislav Karamin - Programmer-analyst (Python, SQL, BI, Statistics)"
description: "Programmer-analyst with skills in Python, SQL, BI, statistics, and mathematics. I love finding patterns in data and turning them into understandable reports. Currently, my main priority is developing my skills in analytics, programming, and mathematics."
url: "https://ksp-hub.github.io" # Без слеша в конце
baseurl: "" # Оставьте пустым для username.github.io

# About the author
author:
  name: "Karamin Stanislav Pavlovich"
  email: "karamin.stanislav@gmail.com"
  github: "KSP-Hub" # Только username, не полный URL
  bio: "Programmer-analyst specializing in Python, SQL, BI, and statistics"

# Theme settings
theme: jekyll-theme-cayman

# Display settings
show_downloads: false
google_analytics: "" # Ваш Google Analytics ID если нужен

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# SEO settings
logo: "/assets/images/logo.png" # Путь к логотипу
twitter_username: "karaminsp" # Ваш Twitter если есть
linkedin_username: "karamin-stanislav" # Ваш LinkedIn если есть

# Custom settings
custom_skills:
  - "Python & Data Analysis"
  - "SQL & Databases"
  - "BI & Data Visualization"
  - "Statistics & Mathematics"

custom_projects:
  main: "Data Analysis Projects"
  status: "Active Learning"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclusions from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Inclusions
include:
  - .well-known

# Sass settings
sass:
  sass_dir: _sass
  style: compressed
