# Basic website settings
title: "Stanislav Karamin - Programmer-analyst (Python, SQL, BI, Statistics)"
description: "Programmer-analyst with skills in Python, SQL, BI, statistics, and mathematics;<br><br>I love finding patterns in data and turning them into understandable reports; <br><br>Currently, my main priority and incredible passion is developing my skills in the academic and professional fields of analytics, programming, and mathematics."
url: "https://ksp-hub.github.io/" # Ваш URL
baseurl: "" # Оставьте пустым для username.github.io

# About the author
author:
  name: "Karamin Stanislav Pavlovich"
  email: "karamin.stanislav@gmail.com"
  github: "https://ksp-hub.github.io/"
  bio: "Programmer-analyst with skills in Python, SQL, BI, statistics, and mathematics;<br><br>I love finding patterns in data and turning them into understandable reports; <br><br>Currently, my main priority and incredible passion is developing my skills in the academic and professional fields of analytics, programming, and mathematics."

# Theme settings
theme: jekyll-theme-cayman
# Other available topics:
# - jekyll-theme-minimal
# - jekyll-theme-hacker
# - jekyll-theme-merlot
# - jekyll-theme-time-machine

# Display settings
show_downloads: false
google_analytics: "" # Ваш Google Analytics ID если нужен
github:
  repository_url: "https://github.com/KSP-Hub"

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# SEO settings
logo: "/assets/images/logo.png" # Путь к логотипу
twitter_username: "karaminsp" # Ваш Twitter если есть
linkedin_username: "karamin-stanislav" # Ваш LinkedIn если есть

========
========

## EDUCATIONAL VECTOR ↴
1. Complete courses on [Fundamentals of Statistics](https://stepik.org/course/76/promo?auth=login);
2. Take courses on [Probability Theory and Mathematical Statistics](https://ru.khanacademy.org/math/statistics-probability);
3. Take courses on [Interactive SQL Trainer](https://stepik.org/course/63054/promo#toc);
4. Complete courses on [Python Generation 1-3 lvl](https://stepik.org/org/pygen);
5. Learn C++ as a second programming language [CS Center](https://stepik.org/org/compscicenter);
6. Achieve B1 level English proficiency;
7. Complete a two-year master's program in machine learning at HSE.

## LONG-TERM GOALS AND EXPECTATIONS ↴
1. Degree in computer science;
2. Create competitive solutions that solve business and community problems by creating commercial products, including open source products, that are useful and professional in the global market. Under the “Made in Russia” quality mark.

## SET OF TECHNOLOGIES ↴

|Name     |Technology                                           | 
|:----------:     |:------------------------------------------------:   |
| **Languages**       | Python, SQL, Markdown                               |
| **Spreadsheets** | MS Excel, G Sheets, Р7, OpenOffice                  |
| **Databases** | ClickHouse, PostgreSQL, Dbeaver                     |
| **Tools** | Git, GitHub, Anaconda, Jupyter, Google Colab, VS Code, PyCharm, Datalens|
| **Concepts**   | Object-oriented programming (OOP)     |


## EXAMPLES OF MY WORK ↴

|Name                                       | Technology | Description                                  |Date      | Link |
|:-------------- ------------------------------------|:-------------|:---------:|:-----|:-----:|
| **Data collection, processing, and structuring** | Anaconda, Python, Jupyter | **Task:** Working with the “openpyxl, docx” modules in Jupyter notebook | 09.09.2025 | [link to file LB1.ipynb] (https://github.com/karamin-stanislav/Tasks-Solutions-Data-Analysis/blob/2bd79b00ff8fdafbce252624fb2f788ae08862dd/20250909%20%D0%9B%D0%90%D0%911.%20% D0%A1%D0%B1%D0%BE%D1%80%2C%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82% D0%BA%D0%B0%20%D0%B8%20%D1%81%D1%82%D1%80%D1%83%D0%BA% D1%82%D1%83%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%B4%D0%B0%D0%BD%D0%BD% D1%8B%D1%85%20%D0%A1.%20%D0%9F.%20%D0%9A%D0%B0%D1%80%D0%B0%D0%BC% D0%B8%D0%BD%202025%20%D0%A0%D0%95%D0%A8%D0%95%D0%9D%D0%98%D0%95.ipynb)|
|**Fundamentals of Data Analysis in Python**             | Anaconda, Python, Jupyter |**1. Task 1:** Create a Series, clean the DataFrame, analyze grocery store data.<br>**2. Task** 2: Research borrowers. Client: Bank credit department. Libraries: pandas, numpy, matplotlib. Client: Bank credit department.|  September 15, 2025 | [link to file LB2.ipynb] (https://github.com/karamin-stanislav/Tasks-Solutions-Data-Analysis/blob/5714d10669aa4a3879358833b89aa6fecae0b8c0/20250915%20%D0%9B%D0%912.%20% D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%20%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%20%D0%B4%D0%B0%D0%BD% D0%BD%D1%8B%D1%85%20%D0%B2%20Python.%20%D0%A0%D0%95%D0%A8% D0%95%D0%9D%D0%98%D0%95.%20%D0%A1.%20%D0%9F.%20%D0%9A%D0%B0%D1%80%D0%B0%D0%BC% D0%B8%D0%BD.%2007.10.2025.ipynb)|
|**Fundamentals of statistics for data analysis and statistical tools in Excel**| MS Excel| **Task:** Conduct a comprehensive statistical and analytical analysis of the company's sales for the period 2021-2023, identify trends, test hypotheses, and provide practical recommendations for the business. Perform regression analysis based on the provided dataset for regressions.| 09/26/2025 | [link to file LB3.xlsx](https://github.com/karamin-stanislav/Tasks-Solutions-Data-Analysis/blob/5714d10669aa4a3879358833b89aa6fecae0b8c0/20250926%20% D0%9B%D0%913.%20Excel.%20%D0%A1.%D0%9F.%20%D0%9A%D0%B0%D1%80%D0%B0%D0%BC% D0%B8%D0%BD%20%D0%A0%D0%95%D0%A8%D0%95%D0%9D%D0%98%D0%95.xlsx)|
|**SQL Basics for Analysts**      |PostgreSQL, Dbeaver, SQL|**Task:** Complete and prepare a report in .docx format.<br>Dataset: https://www.kaggle.com/datasets/smayanj/e-commerce-transactions-dataset | 09/28/2025 | [link to file LB4.docx](https://github.com/karamin-stanislav/Tasks-Solutions-Data-Analysis/blob/df8045988af987211f18bfc0d1bccc02ad23cb55/20250928%20% D0%9B%D0%914%20E-commerce-transactions-dataset%20%E2%80%94%20%D0%A0%D0%95%D0%A8% D0%95%D0%9D%D0%98%D0%95.%20%D0%A1.%20%D0%9F.%20%D0%9A%D0%B0%D1%80%D0%B0%D0%BC%D0%B8%D0%BD.docx)|
|**Data visualization using Yandex DataLens.<br>Dashboard creation. <br>Analysis**      |BI: Datalens, CSV, ClickHouse, SQL| **Task:** Analyze sales in a large online store for 2007-2025 <br> And prepare a dashboard for management that will answer key business questions.| 10/02/2025 | [l2 Dashboard_E_Com_LB5](https://datalens.yandex/28ci2emzzssen)<br> [l2 Dashboard_E_Com_LB5.pdf](https://github.com/karamin-stanislav/Tasks-Solutions-Data-Analysis/blob/95c0c16aad4e36638aeebc205a28

---
# Кастомные настройки
(test) java_skills:
  - "Java & JavaFX"
  - "Clean Architecture"
  - "Git & GitHub workflows"
  - "Maven Build System"

(test) projects:
  main: "Java Beauty Suite"
  status: "Active Development"
---

========
========

# Настройки сборки
markdown: kramdown
highlighter: rouge
permalink: pretty

# Исключения из сборки
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Включения
include:
  - .well-known

# Настройки Sass
sass:
  sass_dir: _sass
  style: compressed
